"""create all tables

Revision ID: 7271ea76b189
Revises: 687223ddaf6b
Create Date: 2026-07-21 02:11:03.008029
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '7271ea76b189'
down_revision: Union[str, None] = '687223ddaf6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acervo_digital',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('arquivo_id', sa.String(length=255), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('tipo_arquivo', sa.String(length=100), nullable=True),
    sa.Column('link_google_drive', sa.Text(), nullable=True),
    sa.Column('link_download_python', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_acervo_digital_arquivo_id'), 'acervo_digital', ['arquivo_id'], unique=True)
    op.create_table('aprendizagens_essenciais',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ano_referencia', sa.Integer(), nullable=False),
    sa.Column('etapa', sa.String(length=20), nullable=False),
    sa.Column('componente', sa.String(length=50), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('id_ae', sa.String(length=20), nullable=False),
    sa.Column('prefixo', sa.String(length=10), nullable=False),
    sa.Column('codigo_ae', sa.String(length=10), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('habilidade_priorizada', sa.String(length=20), nullable=False),
    sa.Column('habilidades_relacionadas', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('conhecimentos_previos', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('prova_paulista', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('saresp', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('desenvolvimento_aprendizagem', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ano_referencia', 'id_ae', name='uq_aprendizagem_essencial')
    )
    op.create_index(op.f('ix_aprendizagens_essenciais_ano'), 'aprendizagens_essenciais', ['ano'], unique=False)
    op.create_index(op.f('ix_aprendizagens_essenciais_ano_referencia'), 'aprendizagens_essenciais', ['ano_referencia'], unique=False)
    op.create_index(op.f('ix_aprendizagens_essenciais_componente'), 'aprendizagens_essenciais', ['componente'], unique=False)
    op.create_index(op.f('ix_aprendizagens_essenciais_etapa'), 'aprendizagens_essenciais', ['etapa'], unique=False)
    op.create_index(op.f('ix_aprendizagens_essenciais_habilidade_priorizada'), 'aprendizagens_essenciais', ['habilidade_priorizada'], unique=False)
    op.create_index(op.f('ix_aprendizagens_essenciais_id_ae'), 'aprendizagens_essenciais', ['id_ae'], unique=True)
    op.create_index(op.f('ix_aprendizagens_essenciais_prefixo'), 'aprendizagens_essenciais', ['prefixo'], unique=False)
    op.create_table('escolas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('endereco', sa.Text(), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('escopo_sequencia',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ano_referencia', sa.Integer(), nullable=False),
    sa.Column('etapa', sa.String(length=20), nullable=False),
    sa.Column('componente', sa.String(length=50), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('id_ae', sa.String(length=20), nullable=False),
    sa.Column('prefixo_ae', sa.String(length=10), nullable=False),
    sa.Column('id_aula', sa.String(length=30), nullable=False),
    sa.Column('aula', sa.String(length=20), nullable=True),
    sa.Column('conteudo', sa.Text(), nullable=True),
    sa.Column('objetivos_aprendizagem', sa.Text(), nullable=True),
    sa.Column('habilidades', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('aprendizagem_essencial', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('pagina_pdf', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ano_referencia', 'id_aula', 'aula', 'pagina_pdf', name='uq_escopo_sequencia')
    )
    op.create_index(op.f('ix_escopo_sequencia_ano'), 'escopo_sequencia', ['ano'], unique=False)
    op.create_index(op.f('ix_escopo_sequencia_ano_referencia'), 'escopo_sequencia', ['ano_referencia'], unique=False)
    op.create_index(op.f('ix_escopo_sequencia_componente'), 'escopo_sequencia', ['componente'], unique=False)
    op.create_index(op.f('ix_escopo_sequencia_etapa'), 'escopo_sequencia', ['etapa'], unique=False)
    op.create_index(op.f('ix_escopo_sequencia_id_ae'), 'escopo_sequencia', ['id_ae'], unique=False)
    op.create_index(op.f('ix_escopo_sequencia_id_aula'), 'escopo_sequencia', ['id_aula'], unique=False)
    op.create_index(op.f('ix_escopo_sequencia_prefixo_ae'), 'escopo_sequencia', ['prefixo_ae'], unique=False)
    op.create_table('materiais_didaticos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ano_referencia', sa.Integer(), nullable=False),
    sa.Column('bimestre', sa.Integer(), nullable=False),
    sa.Column('serie', sa.String(length=10), nullable=False),
    sa.Column('componente', sa.String(length=50), nullable=False),
    sa.Column('cod_cronograma', sa.Integer(), nullable=False),
    sa.Column('id_cronograma', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=True),
    sa.Column('referencia_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=100), nullable=True),
    sa.Column('ordenacao', sa.Integer(), nullable=True),
    sa.Column('semana', sa.Integer(), nullable=True),
    sa.Column('aulas_com_tarefa', sa.Boolean(), nullable=True),
    sa.Column('link_url_youtube', sa.Text(), nullable=True),
    sa.Column('exibir_municipio', sa.Boolean(), nullable=True),
    sa.Column('arquivos', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('array_links_youtube', sa.Text(), nullable=True),
    sa.Column('id_aula', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_materiais_didaticos_id_aula'), 'materiais_didaticos', ['id_aula'], unique=False)
    op.create_table('disciplinas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=True),
    sa.Column('escola_id', sa.UUID(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['escola_id'], ['escolas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('escola_id', sa.UUID(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['escola_id'], ['escolas.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('professores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('escola_id', sa.UUID(), nullable=True),
    sa.Column('formacao', sa.Text(), nullable=True),
    sa.Column('especialidade', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['escola_id'], ['escolas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_table('provas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('disciplina_id', sa.UUID(), nullable=True),
    sa.Column('professor_id', sa.UUID(), nullable=True),
    sa.Column('data_aplicacao', sa.Date(), nullable=True),
    sa.Column('duracao_minutos', sa.Integer(), nullable=True),
    sa.Column('peso', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['disciplina_id'], ['disciplinas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['professor_id'], ['professores.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('turmas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('serie', sa.String(length=50), nullable=True),
    sa.Column('turno', sa.String(length=20), nullable=True),
    sa.Column('escola_id', sa.UUID(), nullable=True),
    sa.Column('professor_id', sa.UUID(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['escola_id'], ['escolas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['professor_id'], ['professores.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matriculas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('aluno_id', sa.UUID(), nullable=True),
    sa.Column('turma_id', sa.UUID(), nullable=True),
    sa.Column('data_matricula', sa.Date(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['turma_id'], ['turmas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aluno_id', 'turma_id')
    )
    op.create_table('provas_turmas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('prova_id', sa.UUID(), nullable=True),
    sa.Column('turma_id', sa.UUID(), nullable=True),
    sa.Column('data_agendada', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['prova_id'], ['provas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['turma_id'], ['turmas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prova_id', 'turma_id')
    )
    op.create_table('questoes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('prova_id', sa.UUID(), nullable=True),
    sa.Column('enunciado', sa.Text(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('pontos', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['prova_id'], ['provas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alternativas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('questao_id', sa.UUID(), nullable=True),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('correta', sa.Boolean(), nullable=True),
    sa.Column('letra', sa.CHAR(length=1), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['questao_id'], ['questoes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('respostas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('questao_id', sa.UUID(), nullable=True),
    sa.Column('aluno_id', sa.UUID(), nullable=True),
    sa.Column('alternativa_id', sa.UUID(), nullable=True),
    sa.Column('texto_dissertativo', sa.Text(), nullable=True),
    sa.Column('nota', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('corrigida', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['alternativa_id'], ['alternativas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['aluno_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['questao_id'], ['questoes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('respostas')
    op.drop_table('alternativas')
    op.drop_table('questoes')
    op.drop_table('provas_turmas')
    op.drop_table('matriculas')
    op.drop_table('turmas')
    op.drop_table('provas')
    op.drop_table('professores')
    op.drop_table('usuarios')
    op.drop_table('disciplinas')
    op.drop_index(op.f('ix_materiais_didaticos_id_aula'), table_name='materiais_didaticos')
    op.drop_table('materiais_didaticos')
    op.drop_index(op.f('ix_escopo_sequencia_prefixo_ae'), table_name='escopo_sequencia')
    op.drop_index(op.f('ix_escopo_sequencia_id_aula'), table_name='escopo_sequencia')
    op.drop_index(op.f('ix_escopo_sequencia_id_ae'), table_name='escopo_sequencia')
    op.drop_index(op.f('ix_escopo_sequencia_etapa'), table_name='escopo_sequencia')
    op.drop_index(op.f('ix_escopo_sequencia_componente'), table_name='escopo_sequencia')
    op.drop_index(op.f('ix_escopo_sequencia_ano_referencia'), table_name='escopo_sequencia')
    op.drop_index(op.f('ix_escopo_sequencia_ano'), table_name='escopo_sequencia')
    op.drop_table('escopo_sequencia')
    op.drop_table('escolas')
    op.drop_index(op.f('ix_aprendizagens_essenciais_prefixo'), table_name='aprendizagens_essenciais')
    op.drop_index(op.f('ix_aprendizagens_essenciais_id_ae'), table_name='aprendizagens_essenciais')
    op.drop_index(op.f('ix_aprendizagens_essenciais_habilidade_priorizada'), table_name='aprendizagens_essenciais')
    op.drop_index(op.f('ix_aprendizagens_essenciais_etapa'), table_name='aprendizagens_essenciais')
    op.drop_index(op.f('ix_aprendizagens_essenciais_componente'), table_name='aprendizagens_essenciais')
    op.drop_index(op.f('ix_aprendizagens_essenciais_ano_referencia'), table_name='aprendizagens_essenciais')
    op.drop_index(op.f('ix_aprendizagens_essenciais_ano'), table_name='aprendizagens_essenciais')
    op.drop_table('aprendizagens_essenciais')
    op.drop_index(op.f('ix_acervo_digital_arquivo_id'), table_name='acervo_digital')
    op.drop_table('acervo_digital')
    # ### end Alembic commands ###
