"""Add ConfiguracaoImportacaoHorarios and HorarioAula models

Revision ID: ddcc0efb74ba
Revises: 
Create Date: 2026-09-15 08:20:56.467896
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'ddcc0efb74ba'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracoes_importacao_horarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('escola_id', sa.UUID(), nullable=True),
    sa.Column('tipo_importacao', sa.String(length=50), nullable=False),
    sa.Column('fonte_dados', sa.Text(), nullable=True),
    sa.Column('mapeamento_dias', sa.JSON(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['escola_id'], ['escolas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('escola_id')
    )
    op.create_table('horarios_aulas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('escola_id', sa.UUID(), nullable=True),
    sa.Column('dia_semana', sa.String(length=20), nullable=False),
    sa.Column('horario', sa.String(length=20), nullable=False),
    sa.Column('turma', sa.String(length=50), nullable=False),
    sa.Column('disciplina', sa.String(length=100), nullable=True),
    sa.Column('professor', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['escola_id'], ['escolas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('horarios_aulas')
    op.drop_table('configuracoes_importacao_horarios')
    # ### end Alembic commands ###
