from app.models.models import (
    Escola,
    Usuario,
    Professor,
    Disciplina,
    Turma,
    Matricula,
    Disciplina,
    Prova,
    ProvaTurma,
    Questao,
    Alternativa,
    Resposta,
    MaterialDidatico,
    AprendizagemEssencial,
    EscopoSequencia,
    Base,
)

__all__ = [
    "Base",
    "Escola",
    "Usuario",
    "Professor",
    "Disciplina",
    "Turma",
    "Matricula",
    "Prova",
    "ProvaTurma",
    "Questao",
    "Alternativa",
    "Resposta",
    "MaterialDidatico",
    "AprendizagemEssencial",
    "EscopoSequencia",
]