name: Deploy

on:
  push:
    branches:
      - main

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Preparar diretório no servidor
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.SSH_HOST }}
          username: ${{ vars.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ vars.SSH_PORT }}
          script: |
            sudo mkdir -p /srv/apps
            sudo chown -R $USER:$USER /srv/apps
            sudo chmod -R 775 /srv/apps

      - name: Sincronizar Arquivos
        uses: burnett01/rsync-deployments@7.0.2
        with:
          switches: -avzr --delete
          path: ./
          remote_path: /srv/apps/${{ vars.APP_NAME }}
          remote_host: ${{ vars.SSH_HOST }}
          remote_user: ${{ vars.SSH_USER }}
          remote_key: ${{ secrets.SSH_KEY }}

      - name: Reiniciar Serviço
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.SSH_HOST }}
          username: ${{ vars.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ vars.SSH_PORT }}
          script: |
            docker stack deploy -c /srv/apps/geduc/infra/lablrovas.yaml apps
